### ISSUE TITLE
PluginVersion + Add BPAtmo

### ISSUE THREAD

**Issue by BenjaCorp** [Dimev/Realistic-Atmosphere-Godot-and-UE4#5]
![UE4Editor_HScRvvuKjK](https://user-images.githubusercontent.com/19375442/124042473-31ccd380-da09-11eb-993f-913c5feb0e3d.png)

Download : [https://cdn.discordapp.com/attachments/760187471056207897/859954729327919134/RealisticAtmospherePluginUE4.26-24.7z](url)

Bye 

if you want make planet, use **planetcore** plugin :p

**Comment by Dimev** [comment]
What's exactly inside this plugin?

**Comment by Dimev** [comment]
Ok added
