### ISSUE TITLE
Which UE Version to use, UE 4.26.1 Spitting out Errors in the atmosphere_non_post material

### ISSUE THREAD

**Issue by echomusician** [Dimev/Realistic-Atmosphere-Godot-and-UE4#8]
These are the errors.
![image](https://user-images.githubusercontent.com/77608590/155772534-e52e98b1-9f6b-45ef-9298-4cd920f5e58d.png)

i would like to share more information but i dont know what to share

**Comment by Dimev** [comment]
22.3 is the one I made it originally with. Afaik it *should* work but it doesn't. I'll check

In the meantime you can port your own with this (not finished) guide: https://github.com/Dimev/shadertoy-to-unreal-engine

**Comment by Dimev** [comment]
Also which one did you download?
There's also the 4.25 ver, might already fix it.

**Comment by Dimev** [comment]
Also, can you try it in 4.26.0?

**Comment by echomusician** [comment]
No i cannot, only avalible version is... 4.26.2? oh i was wrong its 26.2 though i dont think that has to much differences.
btw are you the guy behind the Saturn (or jupiter i cant remember) Project?

**Comment by Dimev** [comment]
nope, I'm someone else.

**Comment by echomusician** [comment]
Okay, also i am trying 4.25.4 and lets see if that fixes anything

**Comment by Dimev** [comment]
btw which file did you get?

**Comment by echomusician** [comment]
Sorry what? do you mean what i downloaded?

**Comment by Dimev** [comment]
yes

**Comment by echomusician** [comment]
UpdatedAtmosphere.zip

wait a minute im realizing im stupid you have nothing to do with the "newer" version by the other guy... oh well
im sorry for taking your time

but instead i have question, whats the add-on supposed to be for this atmosphere shader

**Comment by Dimev** [comment]
Lol
Not entirely sure who/what you're talking about. 

The new "RealisticAtmospherePluginUE4.26-24.7z" one was made by someone else that made it a plugin (and severely overengineered it) and is not supported/made by me, only reason I included it was to not have to deal with him trying to force me to change this plugin in a way he wanted. The "Atmo_Demo_2 4.25.zip" is probably what you want, as it includes a demo of what you need to set up.
